### ISSUE TITLE
Change behavior on errors

### ISSUE THREAD

**Issue by kazie** [eric-von-knorring/youtube-search#1]
The error handling could be improved some.
Here are my thoughts marked as diff:

```diff
response, err := http.Get("https://www.youtube.com/results?search_query=" + searchQuery)
if err != nil {
+	// If we get connection errros (internet down, firewall, etc) maybe print them before exit?
+	log.Fatal("Could not perform 'get' towards youtube. ", err)
	os.Exit(127)
}
defer response.Body.Close()

document, err := goquery.NewDocumentFromReader(response.Body)
if err != nil {
	log.Fatal("Error open search result response body. ", err)
+	// If error maybe exit?
+	os.Exit(128)
}

template, err := template.New("output").Parse(Format)
if err != nil {
	log.Fatal("Could not parse format flag from as go template")
+	// If error maybe exit?
+	os.Exit(129)
}
```

**Comment by kazie** [comment]
Example error that could be missed in the first `nil`-check:

```
./youtube-search 'Hello'
2020/01/24 08:13:59 Could not perform 'get' towards youtube. Get https://www.youtube.com/results?search_query=Hello: dial tcp: lookup www.youtube.com on [::1]:53: read udp [::1]:58262->[::1]:53: read: connection refused
```

Which makes me think that maybe it would be good to have a newline before printing the `err` itself.

**Comment by eric-von-knorring** [comment]
Ok, so what I gather from this ticket is that you want to do two feature request.

1. Adding extra stderr output when not being able to reach youtube.
2. Changing exit codes from 1 to specific ones for each error.

Also the supplied diff can not be applied since all of the `os.Exit(...)` are all unreachable.
I also don't understand the "maybe exit?" since it is already terminating the program with both `log.Fatal` and `os.Exit` it shouldn't be more like "// EXIT !" ;p

As for request 1, I think most people are going to notice that it is not connecting just by not output and network issues are generrally felt in more critical programs first. But I am advocator clear error messages when something fails so I think this should be added.

As for request 2, I am not sure this really is usefully unless there is a need to script around the if what type of parsing failure that has occurred. To my knowledge this not a real use-case. If I am wrong can you please provide an example use-case otherwise I am content with keeping exit code 1 as a "general error" status code.

Lastly I notice that the sentence "Could not parse format flag from as go template" does not make sense. Will fix.

**Comment by eric-von-knorring** [comment]
Also updated the title since it is not about adding error handling but more about how behaviors during error handling

**Comment by kazie** [comment]
Yes, for 
1) The program would fail silently with an error code `127` for any reason `http.Get` would return an error. Without writing the error out. The code itself `127` is also indeterministic and not documented leading to anyone not reading the source code not understanding why it isn't working.

2. Ah OK, I was not aware of that `log.Fatal` (apart from `log.xxx` returns the code with error code `1`.).

**Comment by kazie** [comment]
> *Also the supplied diff...*

Yes. As written it was not intended as a PR diff but as stated above.
> *Here are my thoughts marked as diff:*

**Comment by eric-von-knorring** [comment]
Changes regarding error messages have already been pushed to master also regarding documentation there already exists a ticket to add the exit codes to the man-page (see #2 ).
